source 'https://rubygems.org'

# core
gem 'rails',          '4.2.1'
gem 'puma',           '~> 2.11'

# redis
gem 'hiredis',        '~> 0.4.0'
gem 'redis',          '>= 2.2.0', :require => ['redis', 'redis/connection/hiredis']
gem 'redis-rails',    '~> 4.0'

# views
gem 'sass-rails',     '~> 5.0'
gem 'haml-rails',     '~> 0.9'
gem 'jquery-rails',   '~> 4.0'
gem 'jbuilder',       '~> 2.0'
gem 'uglifier',       '>= 1.3'

platform :ruby do
  gem 'therubyracer', '~> 0.12'
  gem 'pg',           '~> 0.18'
end

platform :jruby do
  gem 'therubyrhino', '~> 1.73'
  gem 'activerecord-jdbc-adapter',           '~> 1.3'
  gem 'activerecord-jdbcpostgresql-adapter', '~> 1.3'
end

# dev/test tools
group :development, :test do
  gem 'pry',          '~> 0.10'
  gem 'rspec',        '~> 3.2'
end